packages: []
catalogs:
  build:
    tsdown: ^0.16.1
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.4
    taze: ^19.9.0
  lint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  network:
    ofetch: ^1.5.1
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    pathe: ^2.0.3
  script:
    tsx: ^4.20.6
  test:
    vitest: ^4.0.8
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.10.0
    '@types/prompts': ^2.4.9
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
